;last change 2015-05-30

(load (merge-pathnames "implspecific" *load-pathname*))

(load (merge-pathnames "dateprocs" *load-pathname*))

;traditionally schedules have been using a reddish background for the
;top row (meeting dates); bluish for the leftmost column (role names);
;and white for the rest.  Use the same color coding, but more muted.
;Also, use zebra rows and eschew rules

;(defvar *meeting-date-color* "#99ccff")
;(defvar *role-name-color* "#ffcc99")

(defvar *meeting-date-color* "#f0e0e0") ;reddish
(defvar *role-name-color* "#d0d0f0") ;bluish
(defvar *odd-row-color* "#e0e0e0") ;gray

(defun html-title (title o)
  (format o "<!DOCTYPE html>~%")
  (format o "<html>~%")
  (format o "<!--~%Generated by club3, v. ~a~%" *version*)
  (format o "~a~%" *copyright*)
  (format o "(running on ~a ~a, ~a)~%"
          (lisp-implementation-type) (lisp-implementation-version)
          (machine-type))
  (format o "For details please see ~a~%" *website*)
  (format o "-->~%")
  (format o "<head>~%")
  (format o "<meta charset=\"UTF-8\">~%")
  (format o "<style>~%")
  (format o ".meetingdate { background-color: ~a; font-weight: bold; }~%"
          *meeting-date-color*)
  (format o ".rolename { background-color: ~a; font-weight: bold; }~%"
          *role-name-color*)
  (format o ".oddrow { background-color: ~a; }~%"
          *odd-row-color*)
  (format o ".doublespaced { margin-bottom: 2ex; }~%")
  (format o "a:hover { text-decoration: none; background-color: yellow; }~%")
  (format o "</style>~%")
  (format o "<title>~a</title>~%" title)
  (format o "</head>~%"))
